# -*- coding: utf-8 -*-
"""utils/preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4gddxuJR00dxf3NQl_4mggSW8rYPNyD
"""

import numpy as np
import pandas as pd

def build_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    eps = 1e-8

    df["binder"] = df["cement"] + df["blast_furnace_slag"] + df["fly_ash"]
    df["water_binder_ratio"] = df["water"] / (df["binder"] + eps)

    df["total_aggregate"] = df["coarse_aggregate"] + df["fine_aggregate"]
    df["fine_coarse_ratio"] = df["fine_aggregate"] / (df["coarse_aggregate"] + eps)

    df["slag_frac"] = df["blast_furnace_slag"] / (df["binder"] + eps)
    df["flyash_frac"] = df["fly_ash"] / (df["binder"] + eps)
    df["cement_frac"] = df["cement"] / (df["binder"] + eps)

    df["log_age"] = np.log1p(df["age"])
    df["sqrt_age"] = np.sqrt(df["age"])

    return df
